Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,30 +1,53 @@
-name: Run Python App
+
+name: Validate GitHub Secret Key
 
 on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]
-
 jobs:
-  run-script:
+  validate-secret:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Define expected secret key
+        run: echo "EXPECTED_SECRET=ACTIVITY" >> $GITHUB_ENV
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.9'
+      - name: Validate SECRET_KEY
+        run: |
+          if [ "${{ secrets.SECRET_KEY }}" == "$EXPECTED_SECRET" ]; then
+            echo "SECRET_KEY is valid."
+          else
+            echo "SECRET_KEY is invalid or does not match."
+            exit 1
+          fi
+          
+#name: Run Python App      
+# jobs:
+#   run-script:
+#     runs-on: ubuntu-latest
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
 
-    - name: Run Python script
-      run: |
-        python app.py
+#     - name: Set up Python
+#       uses: actions/setup-python@v4
+#       with:
+#         python-version: '3.9'
+
+#     - name: Install dependencies
+#       run: |
+#         python -m pip install --upgrade pip
+#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+#     - name: Run Python script
+#       run: |
+#         python app.py
+
+
+
+
+
+
 
